[global]
developmentMode = false

[server]
runOnSave = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#96CA00"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
# Mudança principal: Inter → Montserrat
font = "sans serif"

# Nota: O Streamlit não suporta fontes customizadas nativamente no config.toml
# Por isso usamos o CSS no código Python para forçar a fonte Montserrat em todos os elementos